FROM node:22-alpine

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm install

COPY . .

RUN npx prisma generate

EXPOSE 3003

CMD ["sh", "-c", "npx prisma migrate deploy && node src/index.js"]
